// Brahmi site — small interactive touches only.
//
// Loaded by every page (index, privacy, terms, delete-account), so everything
// here guards for elements that may not exist on the page it is running on.

// ── Mobile nav toggle ──────────────────────────────────────
const navToggle = document.querySelector('.nav-toggle');
const navMenu = document.querySelector('.nav-menu');

if (navToggle && navMenu) {
  navToggle.addEventListener('click', () => {
    const open = navMenu.classList.toggle('open');
    navToggle.classList.toggle('open', open);
    navToggle.setAttribute('aria-expanded', String(open));
  });

  // Close the mobile menu after choosing a link.
  navMenu.addEventListener('click', (e) => {
    if (e.target.tagName === 'A') {
      navMenu.classList.remove('open');
      navToggle.classList.remove('open');
      navToggle.setAttribute('aria-expanded', 'false');
    }
  });
}

// ── Theme toggle ───────────────────────────────────────────
//
// Mirrors the app's light/dark switch. The default is the visitor's OS
// setting (handled in CSS by prefers-color-scheme); pressing this stores an
// explicit choice, which the inline snippet in each page's <head> re-applies
// before first paint so there is no flash on the next load.
//
// Injected rather than written into the markup because four pages share this
// navbar and one of them (privacy/terms) is regenerated by bake.py.
(() => {
  const navInner = document.querySelector('.nav-inner');
  if (!navInner || !navToggle) return;

  const root = document.documentElement;
  const KEY = 'brahmi-theme';

  const read = () => {
    try {
      return localStorage.getItem(KEY);
    } catch (e) {
      return null;
    }
  };

  const systemDark = () =>
    window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches;

  const isDark = () => (read() ? read() === 'dark' : systemDark());

  const btn = document.createElement('button');
  btn.className = 'theme-toggle';
  btn.type = 'button';

  const paint = () => {
    const dark = isDark();
    btn.textContent = dark ? '☀' : '☾';
    btn.setAttribute('aria-label', dark ? 'Switch to light theme' : 'Switch to dark theme');
    btn.setAttribute('title', dark ? 'Light theme' : 'Dark theme');
  };

  btn.addEventListener('click', () => {
    const next = isDark() ? 'light' : 'dark';
    root.setAttribute('data-theme', next);
    try {
      localStorage.setItem(KEY, next);
    } catch (e) {
      /* private mode — the toggle still works for this page view */
    }
    paint();
  });

  paint();
  // Last child of the bar: far right on desktop, and CSS `order` puts it back
  // beside the burger on mobile without a second insertion point.
  navInner.appendChild(btn);
})();

// ── FAQ accordion: only one item open at a time ────────────
const faqItems = document.querySelectorAll('.faq-item');
faqItems.forEach((item) => {
  item.addEventListener('toggle', () => {
    if (item.open) {
      faqItems.forEach((other) => {
        if (other !== item) other.open = false;
      });
    }
  });
});

// ── Staggered reveal on scroll ─────────────────────────────
//
// The class is added by JS, never in the markup: with JS off or an old
// browser, nothing is ever hidden.
(() => {
  if (!('IntersectionObserver' in window)) return;
  if (window.matchMedia && window.matchMedia('(prefers-reduced-motion: reduce)').matches) return;

  const targets = document.querySelectorAll(
    '.card, .rung, .badge-block, .phase, .practice, .step, .stat, .faq-item',
  );
  if (!targets.length) return;

  targets.forEach((el) => el.classList.add('js-reveal'));

  const io = new IntersectionObserver(
    (entries) => {
      entries.forEach((entry) => {
        if (!entry.isIntersecting) return;
        const group = Array.from(entry.target.parentElement.children).indexOf(entry.target);
        // 60ms stagger, same as the app's Motion.stagger, capped so a long
        // grid does not leave the last tile waiting a second and a half.
        entry.target.style.transitionDelay = `${Math.min(group, 6) * 60}ms`;
        entry.target.classList.add('in');
        io.unobserve(entry.target);
      });
    },
    { rootMargin: '0px 0px -8% 0px', threshold: 0.06 },
  );

  targets.forEach((el) => io.observe(el));
})();
